### ISSUE TITLE
documantation needed

### ISSUE THREAD

**Issue by fcakyon** [kadirnar/dethub#23]
I couldnt find how to install and use dethub. In readme there is a `run` function but it doesn't show how to import this function.

It would be better if you provided example usage code snippets and installation instructions :)

**Comment by kadirnar** [comment]
Thank you for letting me know. I fixed it. I will add pip and cli support soon.

**Comment by fcakyon** [comment]
@kadirnar usage examples are still missing :) What is `run` function? How to import it?

**Comment by kadirnar** [comment]
You should to run the detect.py file. You should to define the model and image files in the run function.

Yolov5:
https://github.com/kadirnar/dethub/blob/main/detect.py#L36
